services:
  db:
    build: ./db
    ports:
      - "5432:${DB_PORT}"
    env_file:
      - .env
  server:
    build: ./server
    ports:
      - "3000:${SERVER_PORT}"
    env_file:
      - .env
  app:
    build: ./app
    ports:
      - "80:${APP_PORT}"
    env_file:
      - .env
